language: node_js
php:
- '12'

cache:
  directories:
  - "$HOME/.npm/cache"

install: npm install

script:
  -  "./node_modules/.bin/jshint ./src"
  -  "./node_modules/.bin/retire"
  -  "./node_modules/.bin/twly"
