language: node_js
node_js:
- '12'
install: npm install
script:
- "./node_modules/.bin/jshint --verbose ./src/"
- "./node_modules/.bin/retire"
- if [ "$TRAVIS_BRANCH" = "master" ]; then "./node_modules/.bin/twly"; fi
deploy:
  provider: heroku
  api_key:
    secure: Qw/eXmb9tAraaDBo4u4ECXZX8i6uNVGvObIy91LAJ7wdd9CNweyapzw213jHgkJnn3Afkk64+v0e4sR/Xsh31XzChz2RCtZqGrhWyNJ4vTvELB3qr00vN7srEJz05N/3CHXHE5jAPggj/yAtL7F+KzFlqxt/gEhtBPSJGW/PYYSBjHKqh0ic16egQKyjxdsNcOZ6YmW0X6BLuDDX4GpdmP/XhMU/TIJT3iXppy3ksQ/4kl5eKf3jxaC1S6n6CriTZqavGGjwWz84kRUIeTgSRTXYkvjjWgkILXeMSsU9Q6iiTifwHiKErQO07d2rcgXS1sFSgW9vZ3RTnpStUBWg1Lyye+AD+oMUiwBcSakDAUKObfJQ1hi7Xmoyw5aV/6FpoLJafbgR/MWy9R4qia/+bfQEmpTjJ38cRGZgnlqrJJGRE21qpp22RMiDX6GHfIdPPv/H6W3KSGRK6mpLCtvJABGBWy8SJSgqFjOgkGhLlTQgM3tC8YvSF2NkYrgWjiy/b49LDvTocQ747NHvpG/6iAalVpqqM7+CHv45kppr6ridPj8dMaYHWKLSavZ+HzMRvE0B54BEfkaa+/RLo3ichbHBupbMOLzFithDMCiJOgmLKA84wlPWrL9/kq+flBuVpenOZwlDlvJtXhgpb4YJ7gbAteIgRHr9bITOMHXSonM=
  app: ipssi-evaluation-cicd
  on:
    branch: dev
    repo: Atrylon/IPSSI_Evaluation_ci_cd
